import { posix } from 'node:path';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const elenaPages = ['elena/', 'elena/works/', 'elena/works/goodbye-yiwu/', 'elena/contact/'];
export function renderElena(page, d) {
  const relative = target => { const path = posix.relative(page, target); return path ? path + (target.endsWith('/') ? '/' : '') : './'; };
  const asset = file => relative('elena/' + file);
  const home = page === elenaPages[0];
  const works = page === elenaPages[1];
  const film = page === elenaPages[2];
  const contact = page === elenaPages[3];
  const f = d.film;
  const title = home ? d.brand : `${works ? 'Works' : film ? f.detailTitle : 'Contact'} — ${d.brand}`;
  const picture = (item, {cover = false, small = false} = {}) => `<img ${cover ? 'class="film-cover" fetchpriority="high"' : 'loading="lazy"'} src="${asset(`images/${item.image}-800.webp`)}" srcset="${asset(`images/${item.image}-800.webp`)} 800w, ${asset(`images/${item.image}-1600.webp`)} 1600w" sizes="${small ? '(max-width: 600px) calc(100vw - 48px), 394px' : cover ? '(max-width: 442px) calc(100vw - 48px), 394px' : '(max-width: 640px) calc(100vw - 48px), (max-width: 1006px) calc((100vw - 72px) / 2), 467px'}" width="1600" height="900" alt="${esc(item.alt)}" decoding="async">`;
  const logo = `<a class="brand" href="${relative('elena/')}" aria-label="LeLe Films — Home"><img src="${asset('images/lele-logo.png')}" width="800" height="799" alt="Le Le / 乐" fetchpriority="high"></a>`;
  const nav = `<nav class="navigation ${home ? 'navigation-home' : ''}" aria-label="Main navigation"><a class="nav-works" href="${relative('elena/works/')}"${works || film ? ' aria-current="'+(works?'page':'true')+'"' : ''}>Works</a>${logo}<a class="nav-contact" href="${relative('elena/contact/')}"${contact ? ' aria-current="page"' : ''}>Contact</a>${home ? '<span class="line line-orange" aria-hidden="true"></span><span class="line line-blue" aria-hidden="true"></span>' : ''}</nav>`;
  let body;
  if (home) body = `<main id="main" class="home"><h1 class="sr-only">${esc(d.brand)}</h1>${nav}<p class="company-intro"><span><strong>${esc(d.brand)}</strong> ${esc(d.intro)}</span> <span>${esc(d.founderLine)}</span></p></main>`;
  else {
    if (works) body = `<main id="main" class="works"><h1 class="sr-only">Works</h1><a class="film-link" href="${relative('elena/works/goodbye-yiwu/')}" aria-label="${esc(f.title)} — view film details">${picture(f.cover, {cover:true, small:true})}<h2>${esc(f.title)} (${esc(f.titleNote)})<span lang="zh">${esc(f.chineseTitle)}</span></h2></a></main>`;
    if (contact) body = `<main id="main" class="contact"><h1 class="sr-only">Contact LeLe Films</h1><div><p>${esc(d.contact.intro)}<br><a class="email" href="mailto:${esc(d.contact.email)}">${esc(d.contact.email)}</a></p><p>Instagram: <a href="${esc(d.contact.instagram)}" target="_blank" rel="noopener noreferrer">${esc(d.contact.instagramLabel)}<span class="sr-only"> (opens in a new tab)</span></a></p></div></main>`;
    if (film) body = `<main id="main" class="film"><header class="film-intro"><h1>${esc(f.detailTitle)}</h1>${picture(f.cover,{cover:true})}<div class="film-meta"><p>${esc(f.director)}</p><p>${esc(f.format)}</p><p>${esc(f.production)}</p></div></header><div class="film-body"><section aria-labelledby="logline"><h2 id="logline">Logline:</h2><p>${esc(f.logline)}</p></section><section aria-labelledby="support"><h2 id="support">Supported By:</h2><ul class="support-list">${f.support.map(s=>`<li>${esc(s.name)}${s.translation?`<br><span lang="zh">${esc(s.translation)}</span>`:''}${s.award?`<br><em>${esc(s.award).replace('AIDC Award','<strong>AIDC Award</strong>').replace('First Prize','<strong>First Prize</strong>').replace('Best Pitch Award','<strong>Best Pitch Award</strong>')}</em>`:''}</li>`).join('')}</ul></section><section aria-labelledby="stills"><h2 id="stills">Stills:</h2><div class="stills-grid">${f.stills.map(s=>`<figure>${picture(s)}</figure>`).join('')}</div></section><section aria-labelledby="press"><h2 id="press">Press:</h2><ul class="press-list">${f.press.map(p=>`<li><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.label)}<span aria-hidden="true"> ↗</span><span class="sr-only"> (opens in a new tab)</span></a></li>`).join('')}</ul></section></div></main>`;
    body = `<header class="site-header">${nav}</header>` + body;
  }
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff"><meta name="robots" content="noindex, nofollow"><title>${esc(title)}</title><meta name="description" content="${esc(home||contact ? `${d.brand} ${d.intro} ${d.founderLine}` : f.logline)}"><link rel="icon" href="${asset('images/lele-logo.png')}"><link rel="preload" href="${asset('fonts/Barlow-Regular.woff2')}" as="font" type="font/woff2" crossorigin><link rel="preload" href="${asset('fonts/OpenSauceOne-Regular.ttf')}" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${asset('elena.css')}"><script src="${asset('elena.js')}" defer></script></head><body class="page-${home?'home':works?'works':film?'film':'contact'}"><a class="skip-link" href="#main">Skip to content</a>${body}</body></html>`;
}
