import { posix } from 'node:path';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const motionPages = ['motion/', 'motion/works/', 'motion/works/goodbye-yiwu/', 'motion/contact/'];
// The public website (lelefilms.com) is the same edition at the root, without the design-study links, and open to search engines.
export const sitePages = ['', 'works/', 'works/goodbye-yiwu/', 'contact/'];
export const siteOrigin = 'https://lelefilms.com/';
export function renderMotion(page, d, {site = false, assetVersion = ''} = {}) {
  const pages = site ? sitePages : motionPages;
  const version = assetVersion ? `?v=${encodeURIComponent(assetVersion)}` : '';
  const relative = target => { const p = posix.relative(page || '.', target || '.'); return p ? p + (target === '' || target.endsWith('/') ? '/' : '') : './'; };
  const asset = file => relative('elena/' + file);
  const home = page === pages[0], works = page === pages[1], film = page === pages[2], contact = page === pages[3];
  const f = d.film;
  // `sizes` describes how wide each use of a still is drawn, so phones and retina screens fetch the right file.
  const image = (item, {cls = '', eager = false, sizes = '(max-width: 600px) calc(100vw - 48px), 467px'} = {}) => `<img class="${cls}" src="${asset(`images/${item.image}-800.webp`)}" srcset="${asset(`images/${item.image}-800.webp`)} 800w, ${asset(`images/${item.image}-1600.webp`)} 1600w" sizes="${sizes}" width="1600" height="900" alt="${esc(item.alt)}" ${eager ? 'fetchpriority="high" decoding="sync"' : 'loading="lazy" decoding="async"'} draggable="false">`;
  const magnet = (label, href, cls = '', current = '', extra = '') => `<a class="${cls}" href="${href}" data-magnetic${current ? ` aria-current="${current}"` : ''}${extra}><span class="magnetic-inner">${label}</span></a>`;
  const nav = `<nav class="navigation ${home ? 'navigation-home' : ''}" aria-label="Main navigation">${magnet('Works',relative(pages[1]),'nav-works',works?'page':film?'true':'')}<a class="brand" href="${relative(pages[0])}" aria-label="LeLe Films — Home"><img src="${asset('images/lele-logo.png')}" width="800" height="799" alt="Le Le / 乐" fetchpriority="high"></a>${magnet('Contact',relative(pages[3]),'nav-contact',contact?'page':'')}${home?'<span class="line line-orange" aria-hidden="true"></span><span class="line line-blue" aria-hidden="true"></span>':''}</nav>`;
  const footer = site
    ? `<footer class="edition-footer"><span>LELE FILMS</span><a href="${esc(d.contact.instagram)}" target="_blank" rel="noopener noreferrer">Instagram <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a></footer>`
    : `<footer class="edition-footer"><span>LELE FILMS <span aria-hidden="true">/</span> IN MOTION</span><a href="${relative('elena/')}">Original design <span aria-hidden="true">→</span></a></footer>`;
  let body;
  if(home) body = `<main id="main" class="home motion-home"><h1 class="sr-only">${esc(d.brand)}</h1><div class="home-composition">${nav}</div><p class="company-intro"><span><strong>${esc(d.brand)}</strong> ${esc(d.intro)}</span> <span>${esc(d.founderLine)}</span></p><p class="home-note">${esc(d.copyright)}</p></main>`;
  else {
    if(works) body = `<main id="main" class="motion-works"><div class="section-label"><h1>Works</h1><span>01 / SELECTED FILM</span></div><a class="project-row" href="${relative(pages[2])}" data-project aria-label="${esc(f.title)} — view film details" aria-describedby="works-meta"><div class="project-heading"><span class="project-index">01</span><h2>${esc(f.title)}<span class="project-working-title">(${esc(f.titleNote.toLowerCase())})</span><span class="project-chinese" lang="zh">${esc(f.chineseTitle)}</span></h2></div><div class="project-bottom"><span id="works-meta">${esc(f.format)}<br><span class="muted">${esc(f.status)}</span></span></div><div class="project-thumbnail"><div class="project-frame">${image(f.cover,{eager:true,sizes:'(max-width: 600px) calc(100vw - 48px), (max-width: 700px) calc(100vw - 96px), (orientation: portrait) calc(100vw - 96px), (max-width: 1215px) calc(54vw - 54px), 590px'})}</div><span class="project-cta"><span class="project-cta-label">View film</span><span class="project-arrow" aria-hidden="true">→</span></span></div></a><p class="works-note">${esc(f.director)}</p></main>`;
    else if(film) body = `<main id="main" class="film motion-film"><header class="film-intro"><p class="eyebrow-motion">01 / FEATURE DOCUMENTARY</p><h1>${esc(f.detailTitle)}</h1><p class="film-zh" lang="zh">${esc(f.chineseTitle)}</p>${image(f.cover,{cls:'film-cover',eager:true,sizes:'(max-width: 628px) calc(100vw - 48px), 580px'})}<div class="film-meta"><p>${esc(f.director)}</p><p>${esc(f.format)}</p><p>${esc(f.production)}</p></div></header><div class="film-body"><section aria-labelledby="logline"><h2 id="logline">Logline:</h2><p class="logline">${esc(f.logline)}</p></section><section aria-labelledby="support"><h2 id="support">Supported By:</h2><ul class="support-list">${f.support.map(s=>`<li>${esc(s.name)}${s.translation?`<br><span lang="zh">${esc(s.translation)}</span>`:''}${s.award?`<br><em>${esc(s.award)}</em>`:''}</li>`).join('')}</ul></section><section class="stills-section" aria-labelledby="stills"><h2 id="stills">Stills:</h2><div class="stills-grid">${f.stills.map(s=>image(s,{sizes:'(max-width: 480px) calc(100vw - 48px), (max-width: 940px) calc(50vw - 48px), 422px'})).join('')}</div></section><section class="director-section" aria-labelledby="director"><h2 id="director">Director:</h2><div class="director-layout"><img class="director-portrait" src="${relative(f.directorBio.portrait.image)}" alt="${esc(f.directorBio.portrait.alt)}" width="${f.directorBio.portrait.width}" height="${f.directorBio.portrait.height}" loading="lazy" decoding="async"><div class="director-bio"><p><strong>${esc(f.directorBio.name)}</strong> ${esc(f.directorBio.intro)}</p>${f.directorBio.paragraphs.map(p=>`<p>${esc(p).replace('The Acupuncturist','<em>The Acupuncturist</em>').replace('Goodbye, Yiwu','<em>Goodbye, Yiwu</em>')}</p>`).join('')}</div></div></section><section aria-labelledby="press"><h2 id="press">Press:</h2><ul class="press-list">${f.press.map(p=>`<li><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.url)}<span class="sr-only"> (opens in a new tab)</span></a></li>`).join('')}</ul></section><nav class="film-next" aria-label="Continue"><a href="${relative(pages[1])}"><span aria-hidden="true">←</span>&nbsp;Works</a><a href="${relative(pages[3])}" data-magnetic><span class="magnetic-inner">Contact LeLe&nbsp;Films&nbsp;<span aria-hidden="true">→</span></span></a></nav></div></main>`;
    else body = `<main id="main" class="contact motion-contact"><h1 class="sr-only">Contact LeLe Films</h1><div><p>${esc(d.contact.intro)}</p>${magnet(esc(d.contact.email),`mailto:${esc(d.contact.email)}`,'email contact-email','',' draggable="false"')}<p class="copy-line"><button type="button" class="text-button" data-copy="${esc(d.contact.email)}" hidden>Copy email address</button></p><p class="instagram-line">Instagram: <a href="${esc(d.contact.instagram)}" target="_blank" rel="noopener noreferrer">${esc(d.contact.instagramLabel)} <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a></p></div><p class="sr-only" role="status" data-copy-status></p></main>`;
    body = `<header class="site-header">${nav}</header>${body}`;
  }
  const title=home?d.brand:works?'Works':film?f.detailTitle:'Contact';
  const description = home?`${d.brand} ${d.intro} ${d.founderLine}`:f.logline;
  // The design preview stays out of search results; the public site gets its address and a picture for link previews.
  const meta = site
    ? `<title>${esc(home ? d.brand : `${title} — ${d.brand}`)}</title><link rel="canonical" href="${siteOrigin}${page}"><meta property="og:type" content="website"><meta property="og:site_name" content="${esc(d.brand)}"><meta property="og:title" content="${esc(home ? d.brand : `${title} — ${d.brand}`)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${siteOrigin}${page}"><meta property="og:image" content="${siteOrigin}elena/images/${f.cover.image}-1600.webp"><meta property="og:image:alt" content="${esc(f.cover.alt)}"><meta name="twitter:card" content="summary_large_image">`
    : `<meta name="robots" content="noindex, nofollow"><title>${esc(title)} — LeLe in Motion</title>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff">${meta}<meta name="description" content="${esc(description)}"><link rel="icon" href="${asset('images/lele-logo.png')}"><link rel="preload" href="${asset('fonts/Barlow-Regular.woff2')}" as="font" type="font/woff2" crossorigin><link rel="preload" href="${asset('fonts/OpenSauceOne-Regular.ttf')}" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${asset('elena.css')}"><link rel="stylesheet" href="${relative('motion/motion.css')}${version}"><script src="${relative('motion/motion.js')}${version}" defer></script></head><body class="motion-page page-${home?'home':works?'works':film?'film':'contact'}"><a class="skip-link" href="#main">Skip to content</a>${body}${footer}</body></html>`;
}
