import { posix } from 'node:path';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const motionPages = ['motion/', 'motion/works/', 'motion/works/goodbye-yiwu/', 'motion/contact/'];
export function renderMotion(page, d) {
  const relative = target => { const p = posix.relative(page, target); return p ? p + (target.endsWith('/') ? '/' : '') : './'; };
  const asset = file => relative('elena/' + file);
  const home = page === motionPages[0], works = page === motionPages[1], film = page === motionPages[2];
  const f = d.film;
  const image = (item, cls = '', eager = false) => `<img class="${cls}" src="${asset(`images/${item.image}-800.webp`)}" srcset="${asset(`images/${item.image}-800.webp`)} 800w, ${asset(`images/${item.image}-1600.webp`)} 1600w" sizes="(max-width: 700px) 90vw, 600px" width="1600" height="900" alt="${esc(item.alt)}" ${eager ? 'fetchpriority="high"' : 'loading="lazy"'} decoding="async">`;
  const magnet = (label, href, cls = '', current = false) => `<a class="${cls}" href="${href}" data-magnetic${current ? ' aria-current="page"' : ''}><span class="magnetic-inner">${label}</span></a>`;
  const nav = `<nav class="navigation ${home ? 'navigation-home' : ''}" aria-label="Main navigation">${magnet('Works',relative('motion/works/'),'nav-works',works)}<a class="brand" href="${relative('motion/')}" aria-label="LeLe Films — Home"><img src="${asset('images/lele-logo.png')}" width="800" height="799" alt="Le Le / 乐" fetchpriority="high"></a>${magnet('Contact',relative('motion/contact/'),'nav-contact',!home&&!works&&!film)}${home?'<span class="line line-orange" aria-hidden="true"></span><span class="line line-blue" aria-hidden="true"></span>':''}</nav>`;
  const footer = `<footer class="edition-footer"><span>LELE FILMS <span aria-hidden="true">/</span> IN MOTION</span><a href="${relative('elena/')}">Original design <span aria-hidden="true">↗</span></a></footer>`;
  let body;
  if(home) body = `<main id="main" class="home motion-home"><h1 class="sr-only">${esc(d.brand)}</h1><div class="home-composition">${nav}<div class="sticker-stage" aria-label="Objects from Yiwu"><p id="sticker-help" class="sr-only">Drag a sticker. With a sticker focused, use arrow keys to move it, Shift for larger steps, or Escape to reset it.</p>${[['greenery','Artificial greenery',-14],['doll','A boxed toy doll',9],['container','A shipping container',-9]].map(([id,label,angle],i)=>`<button class="sticker sticker-${id}" data-drag style="--angle:${angle}deg" aria-label="Move ${label.toLowerCase()} sticker" aria-describedby="sticker-help" disabled><img src="${relative(`motion/stickers/${id}.webp`)}" alt="${label} — an illustrated sticker inspired by Goodbye, Yiwu" width="360" height="360" draggable="false"><span class="sticker-caption">${String(i+1).padStart(2,'0')} / YIWU</span></button>`).join('')}</div></div><p class="company-intro"><span><strong>${esc(d.brand)}</strong> ${esc(d.intro)}</span> <span>${esc(d.founderLine)}</span></p><div class="home-note"><span class="small-dot" aria-hidden="true"></span><span>Small things. Stories behind them.</span><button type="button" class="text-button" data-reset-stickers hidden>Reset stickers ↺</button><span class="drag-hint" hidden>Pick one up</span></div><p class="sr-only" role="status" data-drag-status></p></main>`;
  else {
    if(works) body = `<main id="main" class="motion-works"><div class="section-label"><h1>Works</h1><span>01 / SELECTED FILM</span></div><a class="project-row" href="${relative('motion/works/goodbye-yiwu/')}" data-project aria-label="${esc(f.title)} — view film details"><div class="project-heading"><span class="project-index">01</span><h2>${esc(f.title)}<span lang="zh">${esc(f.chineseTitle)}</span></h2><span class="project-arrow" aria-hidden="true">↗</span></div><div class="project-bottom"><span>${esc(f.format)}<br><span class="muted">${esc(f.titleNote)}</span></span><div class="project-thumbnail">${image(f.cover,'',true)}<span>View film <span aria-hidden="true">↗</span></span></div></div></a><p class="works-note">${esc(f.director)}</p><div class="floating-preview" aria-hidden="true">${image(f.cover)}<span>View film <span>↗</span></span></div></main>`;
    else if(film) body = `<main id="main" class="film motion-film"><header class="film-intro"><p class="eyebrow-motion">01 / FEATURE DOCUMENTARY</p><h1>${esc(f.detailTitle)}</h1>${image(f.cover,'film-cover',true)}<div class="film-meta"><p>${esc(f.director)}</p><p>${esc(f.format)}</p><p>${esc(f.production)}</p></div></header><div class="film-body"><section aria-labelledby="logline"><h2 id="logline">Logline:</h2><p>${esc(f.logline)}</p></section><section aria-labelledby="support"><h2 id="support">Supported By:</h2><ul class="support-list">${f.support.map(s=>`<li>${esc(s.name)}${s.translation?`<br><span lang="zh">${esc(s.translation)}</span>`:''}${s.award?`<br><em>${esc(s.award)}</em>`:''}</li>`).join('')}</ul></section><section class="stills-section" aria-labelledby="stills"><div class="gallery-heading"><div><h2 id="stills">Stills:</h2><p class="gallery-hint" data-gallery-hint hidden>Pick up a print. Keep looking.</p></div><div class="gallery-controls" hidden><div class="mode-switch" role="group" aria-label="Arrange film stills"><button type="button" data-mode="grid" aria-pressed="true">Grid</button><button type="button" data-mode="desk" aria-pressed="false">Desk <span aria-hidden="true">↗</span></button></div><button class="text-button" type="button" data-reset-photos>Reset ↺</button></div></div><p id="photo-help" class="sr-only">Use the move handle to drag a print. Arrow keys move it, Shift makes larger steps, and Escape resets it. Select the photo to enlarge it.</p><div class="photo-stage" data-layout="grid">${f.stills.map((s,i)=>`<div class="photo-print" data-drag style="--angle:${[-5,5,-3,4][i]}deg"><figure class="print-paper"><a class="photo-open" href="${asset(`images/${s.image}-1600.webp`)}" data-photo="${i}" aria-label="Enlarge still ${i+1}: ${esc(s.alt)}">${image(s)}</a><figcaption><span>YIWU / ${String(i+1).padStart(2,'0')}</span><button type="button" class="photo-grip" aria-label="Move still ${i+1}" aria-describedby="photo-help" hidden>Move <span aria-hidden="true">⠿</span></button><span class="print-open-hint" aria-hidden="true">↗</span></figcaption></figure></div>`).join('')}</div><p class="sr-only" role="status" data-drag-status></p></section><section aria-labelledby="press"><h2 id="press">Press:</h2><ul class="press-list">${f.press.map(p=>`<li><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.label)} <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a></li>`).join('')}</ul></section></div></main><dialog class="photo-dialog" aria-label="Film still viewer"><div class="dialog-toolbar"><span data-photo-count></span><button type="button" data-close aria-label="Close film still viewer">Close ×</button></div><img alt="" data-dialog-image><div class="dialog-bottom"><button type="button" data-previous aria-label="Previous still">←</button><p data-photo-caption></p><button type="button" data-next aria-label="Next still">→</button></div></dialog>`;
    else body = `<main id="main" class="contact motion-contact"><h1 class="sr-only">Contact LeLe Films</h1><div><p>${esc(d.contact.intro)}</p>${magnet(esc(d.contact.email),`mailto:${esc(d.contact.email)}`,'email contact-email')}<p class="instagram-line">Instagram: <a href="${esc(d.contact.instagram)}" target="_blank" rel="noopener noreferrer">${esc(d.contact.instagramLabel)} <span aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></a></p><div class="contact-mark" aria-hidden="true"><span>→</span><span>乐</span></div></div></main>`;
    body = `<header class="site-header">${nav}</header>${body}`;
  }
  const title=home?d.brand:works?'Works':film?f.detailTitle:'Contact';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff"><meta name="robots" content="noindex, nofollow"><title>${esc(title)} — LeLe in Motion</title><meta name="description" content="${esc(home?`${d.brand} ${d.intro} ${d.founderLine}`:f.logline)}"><link rel="icon" href="${asset('images/lele-logo.png')}"><link rel="preload" href="${asset('fonts/Barlow-Regular.woff2')}" as="font" type="font/woff2" crossorigin><link rel="preload" href="${asset('fonts/OpenSauceOne-Regular.ttf')}" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${asset('elena.css')}"><link rel="stylesheet" href="${relative('motion/motion.css')}"><script src="${relative('motion/motion.js')}" defer></script></head><body class="motion-page page-${home?'home':works?'works':film?'film':'contact'}"><a class="skip-link" href="#main">Skip to content</a>${body}${footer}</body></html>`;
}
