const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ext=(url,label,cls='')=>`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label}<span class="sr-only"> (opens in a new tab)</span></a>`;
const img=(p,prefix,cls='',lazy=true)=>`<img class="${cls}" src="${prefix}images/${esc(p.image)}" alt="${esc(p.imageAlt)}" ${lazy?'loading="lazy"':'fetchpriority="high"'} decoding="async" width="1600" height="900">`;
function head(theme,d,p){return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="${theme==='studio'?'#111111':'#171412'}"><title>LELE Films${theme==='compare'?' — Two perspectives':''}</title><meta name="description" content="LELE Films. Independent films and human stories, beginning with the documentary work of Elena Lecun Xiang.">${d.settings?.searchIndexing ? '<meta name="robots" content="index, follow">' : '<meta name="robots" content="noindex, nofollow">'}<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='8' fill='%23171412'/%3E%3Ctext x='12' y='47' fill='%23f1eddf' font-size='43' font-family='Georgia'%3EL%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="${p}site.css"><script src="${p}site.js" defer></script></head><body class="${theme}"><a class="skip-link" href="#main">Skip to content</a>`;}
function dialogs(d,p){return [...d.projects,...d.company.companyProjects].map(f=>`<dialog class="film-dialog" id="${esc(f.id)}" aria-labelledby="${f.id}-title"><button class="dialog-close" aria-label="Close film details" data-close><span aria-hidden="true">×</span></button><div class="dialog-image">${img(f,p,'',true)}<span class="dialog-kicker">${esc(f.format)} · ${esc(f.year)}</span></div><div class="dialog-body"><p class="eyebrow">${esc(f.creditOwner)}</p><h2 id="${f.id}-title">${esc(f.title)}</h2><p class="dialog-chinese" lang="zh">${esc(f.chineseTitle)}</p><div class="film-tags"><span>${esc(f.status)}</span>${f.duration?`<span>${esc(f.duration)}</span>`:''}</div><p class="synopsis">${esc(f.summary)}</p><dl class="credits">${f.credits.map(c=>`<div><dt>${esc(c.role)}</dt><dd>${esc(c.name)}</dd></div>`).join('')}</dl><p class="recognition">${esc(f.recognition)}</p>${f.videoEmbed?`<div class="film-player" data-player="${esc(f.videoEmbed)}"><button class="watch-button" data-play>Play the film <span class="play-triangle" aria-hidden="true"></span></button><p class="player-note">The player loads from Vimeo when you press play.</p></div><p>${ext(f.videoUrl,'Watch on Vimeo','text-link')}</p>`:''}<div class="dialog-links">${f.moreUrl?ext(f.moreUrl,f.videoUrl?'Read the story':'Project details','text-link'):''}${f.sourceUrl?ext(f.sourceUrl,'Original film archive','text-link'):''}${f.poster?`<a class="text-link" href="${p}images/${esc(f.poster)}" target="_blank" rel="noopener noreferrer">View film poster<span class="sr-only"> (opens in a new tab)</span></a>`:''}</div></div></dialog>`).join('');}
function contact(d){return d.company.email?`<a class="contact-link" href="mailto:${esc(d.company.email)}">${esc(d.company.email)}</a>`:`<p class="contact-pending">Our studio is taking shape.<br>Company contact details will be announced here.</p>${ext(d.founder.archiveUrl,'Visit Elena’s film archive','contact-link')}`;}
function writing(d){return `<div class="writing-list">${d.writing.map(w=>ext(w.url,`<span>${esc(w.title)}</span><span class="writing-meta">${esc(w.type)} / ${esc(w.year)}</span>`)).join('')}</div>`;}
function switcher(theme){return `<aside class="design-switch" aria-label="Design comparison"><span>Design ${theme==='quiet'?'01':'02'}</span><a href="../${theme==='quiet'?'studio':'quiet'}/">View ${theme==='quiet'?'Studio':'Quiet Cinema'}</a><a href="../" aria-label="Compare both designs" class="compare-dot">A / B</a></aside>`;}
function quiet(d,p){return `<header class="quiet-header"><nav aria-label="Main navigation"><a href="#films">Films <span lang="zh">影像</span></a><a href="#company">Company <span lang="zh">关于</span></a><a class="quiet-logo" href="./" aria-label="LELE Films home"><span>LELE</span><small>F I L M S</small></a><a href="#notes">Notes <span lang="zh">手记</span></a><a href="#contact">Contact <span lang="zh">联系</span></a></nav></header>
<main id="main"><section class="quiet-work wrap" id="films" aria-labelledby="films-title"><div class="quiet-intro"><p class="eyebrow">Independent cinema · New York & beyond</p><h1 id="films-title">A little closer to real life.</h1><span class="intro-chinese" lang="zh">在影像里，与真实相遇。</span></div><div class="quiet-grid">${d.projects.map((f,i)=>`<article class="quiet-film"><button class="film-cover" data-film="${f.id}" aria-label="Explore ${esc(f.title)}">${img(f,p,'',false)}<span class="cover-border"></span><span class="cover-caption"><span class="cover-title">${esc(f.title)}</span><span lang="zh">${esc(f.chineseTitle)}</span></span><span class="cover-action">Explore film</span></button><div class="film-caption"><div><h2><button data-film="${f.id}">${esc(f.title)}</button></h2><p>${esc(f.format)}${f.duration?' · '+esc(f.duration):''}</p></div><span class="film-year">${esc(f.year)}<small>${f.status==='Work in progress'?'In progress':'Completed'}</small></span></div></article>`).join('')}</div><div class="archive-credit"><span>01 — ${String(d.projects.length).padStart(2,'0')} / Selected films</span><p>From the personal film archive of Elena Lecun Xiang.</p></div></section>
<section class="quiet-company wrap" id="company"><div class="section-topline"><span class="eyebrow">The company / 关于</span><span class="section-number">01</span></div><div class="quiet-company-grid"><h2>Small beginnings.<br><em>Open possibilities.</em></h2><div class="company-copy"><p class="lead">${esc(d.company.intro)}</p><p>${esc(d.company.description)}</p><a class="text-link" href="#elena">Meet the filmmaker</a></div></div></section>
<section class="quiet-founder wrap" id="elena"><div class="founder-picture"><img src="${p}images/${d.founder.portrait}" alt="Elena Lecun Xiang at a documentary industry event" loading="lazy" width="1000" height="667"><span class="photo-caption">The person behind the films.</span></div><div class="founder-copy"><p class="eyebrow">Founder / Filmmaker</p><h2>${esc(d.founder.name)}</h2><p>${esc(d.founder.bio)}</p><p class="founder-role">${esc(d.founder.role)}</p>${ext(d.founder.aboutUrl,'A little more about Elena','text-link')}</div></section>
<section class="quiet-notes wrap" id="notes"><div><p class="eyebrow">From the notebook / 手记</p><h2>Watching.<br>Thinking. Writing.</h2><p>Selected film criticism by Elena.</p></div>${writing(d)}</section>
${additions(d,p,'quiet')}<section class="quiet-contact wrap" id="contact"><p class="eyebrow">A conversation starts somewhere.</p><h2>Let’s make<br><em>room for stories.</em></h2>${contact(d)}</section></main><footer class="quiet-footer wrap"><a href="./">LELE FILMS</a><span>Independent films. Human stories.</span><span>© ${new Date().getUTCFullYear()} LELE Films</span></footer>${dialogs(d,p)}${d.settings?.showDesignSwitcher===false?'':switcher('quiet')}`;}
function studio(d,p){const hero=d.projects.find(f=>f.id===d.settings?.heroProjectId)||d.projects[0];return `<header class="studio-header"><a href="./" class="studio-logo" aria-label="LELE Films home">lele<span>films</span></a><nav aria-label="Main navigation"><a href="#practice">Practice</a><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></nav></header><main id="main"><section class="studio-hero" aria-labelledby="hero-title"><div class="hero-still">${img(hero,p,'',false)}</div><div class="hero-shade"></div><div class="hero-copy"><p class="eyebrow">Independent minds. Shared stories.</p><h1 id="hero-title">${esc(d.company.tagline).replace('. ','.<br>')}</h1><a class="hero-cta" href="#work">Explore our starting point</a></div><div class="hero-footer"><span>A film company by Elena Lecun Xiang</span><span>Frame from ${esc(hero.title)} · ${esc(hero.year)}</span></div><button class="motion-toggle" aria-label="Pause image motion" aria-pressed="false">Pause motion <span aria-hidden="true">Ⅱ</span></button></section>
<section class="studio-practice studio-wrap" id="practice"><p class="eyebrow">LELE Films / A beginning</p><h2>${esc(d.company.intro)}</h2><p class="practice-intro">${esc(d.company.description)}</p><div class="practice-grid"><article><span class="practice-number">01</span><h3>Documentary</h3><p>Time spent listening. Stories shaped by the people who live them.</p></article><article><span class="practice-number">02</span><h3>Cinematography</h3><p>A close attention to people, places and the small details that carry a story.</p></article><article><span class="practice-number">03</span><h3>Editing</h3><p>Finding the rhythm, the relationships and the feeling within the footage.</p></article></div><p class="practice-note">The foundation: Elena’s practice as a filmmaker, cinematographer and editor.</p></section>
<section class="studio-work" id="work"><div class="blue-heading"><h2>Selected work<span class="count">(${String(d.projects.length).padStart(2,'0')})</span></h2><span>Elena’s personal film archive</span></div><div class="studio-film-grid">${d.projects.map(f=>`<article class="studio-film"><button class="studio-film-button" data-film="${f.id}" aria-label="Explore ${esc(f.title)}">${img(f,p)}<span class="studio-film-overlay"><span class="eyebrow">${esc(f.format)} · ${esc(f.year)}</span><span class="studio-film-title">${esc(f.title)}</span><span>${esc(f.chineseTitle)} <span aria-hidden="true">/</span> ${f.status==='Work in progress'?'Work in progress':esc(f.duration)}</span><span class="studio-film-open">Explore film <span aria-hidden="true">+</span></span></span></button></article>`).join('')}</div></section>
<section class="studio-about studio-wrap" id="about"><div class="studio-about-heading"><p class="eyebrow">The filmmaker</p><h2>A personal eye.<br>A collaborative spirit.</h2></div><div class="studio-about-grid"><div class="studio-portrait"><img src="${p}images/${d.founder.portrait}" alt="Elena Lecun Xiang at a documentary industry event" loading="lazy" width="1000" height="667"></div><div><h3>${esc(d.founder.name)}</h3><p class="founder-role">${esc(d.founder.role)}</p><p class="founder-bio">${esc(d.founder.bio)}</p>${ext(d.founder.aboutUrl,'Explore Elena’s archive','text-link')}<div class="studio-note"><p class="eyebrow">Also, on cinema</p>${writing(d)}</div></div></div></section>
${additions(d,p,'studio')}<section class="studio-contact" id="contact"><p class="eyebrow">The next story is still unwritten.</p><h2>Good things<br>start with people.</h2>${contact(d)}<div class="studio-contact-bottom"><a class="studio-logo" href="./">lele<span>films</span></a><span>© ${new Date().getUTCFullYear()} LELE Films</span><a href="#main">Back to top</a></div></section></main>${dialogs(d,p)}${d.settings?.showDesignSwitcher===false?'':switcher('studio')}`;}
function compare(d,p){return `<main id="main" class="comparison"><header class="comparison-header"><span>LELE FILMS</span><span>Two perspectives. One beginning.</span><span>Design study / 2026</span></header><div class="comparison-intro"><p class="eyebrow">A new home for human stories</p><h1>How do you see<br><em>LELE Films?</em></h1><p>Two directions to explore, both beginning with Elena’s real work.</p></div><div class="comparison-grid"><a class="comparison-card quiet-preview" href="quiet/"><div class="comparison-art"><span class="preview-wordmark">LELE <small>F I L M S</small></span>${img(d.projects[0],p,'',false)}</div><div class="comparison-label"><div><span class="eyebrow">01 / Quiet Cinema</span><h2>An intimate frame.</h2><p>Still images. Warm darkness. Room to look closer.</p></div><span class="comparison-open">Open design</span></div></a><a class="comparison-card studio-preview" href="studio/"><div class="comparison-art">${img(d.projects[0],p,'',false)}<span class="preview-statement">Real lives.<br>Lasting stories.</span><span class="preview-blue">lele films / independent cinema</span></div><div class="comparison-label"><div><span class="eyebrow">02 / The Studio</span><h2>A bolder beginning.</h2><p>Cinematic scale. Bold type. A flash of blue.</p></div><span class="comparison-open">Open design</span></div></a></div><footer class="comparison-footer"><p>Selected projects are Elena’s personal work, presented as the foundation for LELE Films.</p>${ext(d.founder.archiveUrl,'Original film archive')}</footer></main>`;}

function additions(d,p,theme){
 const c=d.company,wrap=theme==='quiet'?'wrap':'studio-wrap';
 return (c.companyProjects.length?`<section class="future-section ${wrap}"><p class="eyebrow">LELE Films / Company projects</p><h2>Made together.</h2><div class="future-projects">${c.companyProjects.map(f=>`<article><button class="film-cover" data-film="${esc(f.id)}" aria-label="Explore ${esc(f.title)}">${img(f,p)}<span class="cover-caption"><span class="cover-title">${esc(f.title)}</span></span></button><p>${esc(f.format)} · ${esc(f.year)}</p></article>`).join('')}</div></section>`:'')+
 (c.team.length?`<section class="future-section ${wrap}"><p class="eyebrow">The people</p><h2>Our team.</h2><div class="future-team">${c.team.map(t=>`<article>${t.image?`<img src="${p}images/${esc(t.image)}" alt="${esc(t.name)}" loading="lazy" width="600" height="600">`:''}<h3>${esc(t.name)}</h3><p class="eyebrow">${esc(t.role)}</p><p>${esc(t.bio)}</p></article>`).join('')}</div></section>`:'')+
 (c.services.length?`<section class="future-section ${wrap}"><p class="eyebrow">Working together</p><h2>What we do.</h2><div class="future-team">${c.services.map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></article>`).join('')}</div></section>`:'');
}

export function render(theme,d){const p=theme==='compare'?'./':'../';return head(theme,d,p)+(theme==='quiet'?quiet(d,p):theme==='studio'?studio(d,p):compare(d,p))+'</body></html>';}
